config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#homepage"

  # get "pages/homepage", to: "pages#homepage"

  get "about", to: "pages#about"

  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :deiscription, presence: true, length: {minimum: 10, maximum: 300}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true, 
			  uniqueness: {case_sensitive: false},
			  length: {minimun: 3, maximum: 25}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
			  uniqueness: {case_sensitive: false},
			  length:{maximum: 105},
			  format: { with: VALID_EMAIL_REGEX }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :currunt_user, :logged_in?

	def currunt_user
		@currunt_user ||= User.find(session[:user_id]) if (session[:user_id])
	end

	def logged_in?
		# To return boolean values
		!!currunt_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except:[:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index	
		@articles = Article.paginate(page: params[:page], per_page:5)
	end

	def show
		
	end
	
	def new
		@article = Article.new
	end

	def create
		# render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = currunt_user
		if @article.save 
			flash[:notice] = "Article was sucessfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update 
		if @article.update(article_params)
			flash[:notice] = "Article was sucessfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end	

	def destroy
		@article.destroy
		flash[:notice] = "Artice was successfully deleted"
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end
		def article_params
			params.require(:article).permit(:title, :deiscription)
		end
		def require_same_user
			if currunt_user != @article.user && !currunt_user.admin?
				flash[:danger] = "You can only edit or delete your own article"
				redirect_to root_path
			end
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def homepage
		redirect_to articles_path if logged_in?
	end

	def about

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have sucessfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :set_user, only: [:edit, :update, :show] 
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only:[:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end
	
	def new 
		@user = User.new
	end

	def show
		@user_articles =@user.articles.paginate(page: params[:page], per_page: 5) 
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:sucess] = "Welcome to the Tech blog #{@user.username}"
			redirect_to user_path(@user)
		else	
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all articles have been deleted"
		redirect_to users_path
	end

	private 
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
	def set_user
		@user = User.find(params[:id])
	end
	def require_same_user
		if currunt_user != @user && !currunt_user.admin?
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end
	end
	def require_admin
		if logged_in? && !currunt_user.admin?
			flash[:danger] = "Only admin user can perform that action"
			redirect_to root_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user,options = { size:80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container w-75">
	<% obj.each do |article| %>
		<div class="card text-left">
  			<div class="card-header">
  				<h5><%= link_to article.title, article_path(article), class: "font-weight-bold text-info" %></h5>
			</div>
			<div class="card-body">
			    <!-- <h5 class="card-title">Special title treatment</h5> -->
			    <p class="card-text"><%= article.deiscription %></p>
			    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
			    <div class="article-meta-details mt-4">
				    <small> 
				    	Created By: <%= article.user.username if article.user %>
				    	<%= time_ago_in_words(article.created_at) %> ago,
				    	last update at: <%= time_ago_in_words(article.updated_at) %> ago
				    </small>
				</div>

			</div>
			<% if logged_in? && (currunt_user == article.user || currunt_user.admin?) %>
				<div class="card-footer">
				    <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary pt-0 pb-0" %>	
				    <%= link_to "Delete this article", article_path(article), method: :delete, 
				    					data: {confirm: "Are you sure?"},
				    					class: "btn btn-xs btn-danger pt-0 pb-0" %>
				</div>
			<% end %>
		</div>
		<br>
	<% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj: @article %>

<%= form_for @article do |f| %>
		<div class="form-group">
    		<%= f.label :title %>
    		<%= f.text_field :title, class: "form-control" %>
  		</div>

  		<div class="form-group">
    		<%= f.label :deiscription %>
    		<%= f.text_area :deiscription, class: "form-control" %>
  		</div>
  		<div class="form-group">
  			<%= f.submit(@article.new_record? ? "Create New Artcile" : "Update Article", class: "btn btn-primary btn-lg pt-0 pb-0") %>
  		</div>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1 class="mt-5 text-center mb-5"> Edit existing Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4"> Listing All Articles </h1>
<h6 class="d-flex justify-content-center pl-2 myPagination">
	<%= will_paginate @users ,renderer: BootstrapPagination::Rails %>
</h6>

<%= render "article", obj:@articles %>

<h6 class="d-flex justify-content-center pl-2 myPagination">
	<%= will_paginate @users ,renderer: BootstrapPagination::Rails %>
</h6>

app/views/articles/new.html.erb
<h1 class="mt-5 text-center mb-5">Create New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="mt-5">
	<div class="card text-left">
		<div class="card-header text-center">
		  <h1> <%= link_to @article.title, article_path(@article), class: "font-weight-bold text-info" %> </h1>
		  <h6> Created By: <%= @article.user.username if @article.user %> </h6>
		  <%= link_to(gravatar_for(@article.user), user_path(@article.user), class: "card-img-top mt-3 mb-3") if @article.user %>
		</div>
		<div class="card-body">
		    <!-- <h5 class="card-title">Special title treatment</h5> -->
		    <p class="card-text"><%= @article.deiscription %></p>
		    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
		    <div class="article-meta-details mt-4">
			    <small> 
			    	<%= time_ago_in_words(@article.created_at) %> ago,
			    	last update at: <%= time_ago_in_words(@article.updated_at) %> ago
			    </small>
			</div>

		</div>
		<div class="card-footer">
			<% if logged_in? && (currunt_user == @article.user || currunt_user.admin?) %>
			    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary pt-0 pb-0" %>	
			    <%= link_to "Delete this article", article_path(@article), method: :delete, 
			    					data: {confirm: "Are you sure?"},
			    					class: "btn btn-xs btn-danger pt-0 pb-0" %>
			<% end %>
		    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success pt-0 pb-0" %>
		</div>
	</div>
</div>
<br>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright © <a href="www.zakwanbhaiyat.com" target="_blank">The Complete Ruby on Rails Developer</a>
			by <a href="enter in a link here">Zakwan Bhaiyat</a>

		</small>

		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container mt-4">
	<div class="row">
		<div class="col-12">
			<% flash.each do |name, msg| %>
				<div class='alert alert-<%="#{name}" %>'>
					<a href="#" class="close" data-dismiss="alert">×</a>
					<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				</div>	
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <%= link_to "TechBlog", articles_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link"%>
        </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="#">Link</a> -->
      </li>
      <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Create New Article", new_article_path, class: "dropdown-item"%>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
      <% end %>
      
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
     </form>

    </ul>
    <ul class="navbar-nav ">
      <% if logged_in? %>
         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile <%= "Admin" if currunt_user.admin? %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Edit", edit_user_path(currunt_user), class: "dropdown-item"%>
          <%= link_to "View Profile", user_path(currunt_user), class: "dropdown-item"%>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <!-- <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/navigation' %> 
    <%= render 'layouts/messages' %>
    <div class="container">

      <%= yield %>

    </div>
    <br><br><br>
    <%= render 'layouts/footer' %>
    <br><br><br>
    <hr>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> Welcome to About page </h1>
<%= link_to "Home", root_path %>

app/views/pages/homepage.html.erb
<h1> Welcome to Homepage </h1>

<%= link_to "Alpha Blog", articles_path %> | <%= link_to "About", about_path %>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-12">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from being saved:
					</h2>	
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error', obj: @user %>

<%= form_for @user do |f| %>
		<div class="form-group">
			<div class="col-sm-2">
				<%= f.label :username %> 
			</div>
			<div class="col-sm-12">
				<%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-2">
				<%= f.label :email %>
			</div>
			<div class="col-sm-12">
				<%= f.email_field :email, class: "form-control", placeholder: "Enter Email" %>
			</div>
		</div>


		<div class="form-group">
			<div class="col-sm-2">
				<%= f.label :password %>
			</div>
			<div class="col-sm-12">
				<%= f.password_field :password, class: "form-control", placeholder: "Enter Your Password" %>
			</div>
		</div>


		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-primary btn-lg pt-0 pb-0") %>
			</div>
		</div>
	<% end %>

	<div class="col-xs-4 col-xs-offset-4">
		[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
	</div>

app/views/users/edit.html.erb
<h1 class="mt-3 text-center">Edit your account</h1>

<hr>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4"> All Tech Bloggers </h1>
<hr>
<h6 class="d-flex justify-content-center pl-2 myPagination">
	<%= will_paginate @users ,renderer: BootstrapPagination::Rails %>
</h6>

<center>
	<% @users.each do |user| %>
		<div class="card mb-4 mt-4" style="width: 18rem;">
			<%= link_to gravatar_for(user), user_path(user), class: "card-img-top mt-3 mb-3" %>
		  <div class="card-header">
		    <p class="card-text "><%= link_to user.username, user_path(user) %></p>
		    <p class="card-text"><%= pluralize(user.articles.count, "article") if user.articles %></p>
		    <% if logged_in? and currunt_user.admin? %>
		    	<p>
		    		<%= link_to "Delete this user", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete and all heir articles?"} %>
		    	</p>
		    <% end %>
		  </div>
		</div>
	<% end %>
</center>


<h6 class="d-flex justify-content-center pl-2 myPagination">
	<%= will_paginate @users ,renderer: BootstrapPagination::Rails %>
</h6>

app/views/users/new.html.erb
<h1 class="mt-3 text-center">Sign up for Tech Blog</h1>

<hr>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center" class="mt-4 mb-2"> Welcome to <%= @user.username %>'s page</h1>
<div class="row">
	<div class="col-md-2 col-md-offset-2 rounded mx-auto d-bloc ">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<hr>

<h4 class="text-center"> <%= @user.username %>'s articles </h4>

<h6 class="d-flex justify-content-center pl-2 myPagination">
	<%= will_paginate @user_articles ,renderer: BootstrapPagination::Rails %>
</h6>

<%= render "articles/article", obj: @user_articles %>

<h6 class="d-flex justify-content-center pl-2 myPagination">
	<%= will_paginate @user_articles ,renderer: BootstrapPagination::Rails %>
</h6>